[package]
name = "bf-fast"
version = "0.0.1"
edition = "2018"
authors = ["Zander <CredibleOpossum@protonmail.com>"]
license = "MIT"
description = "A fast brainfuck interpreter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
